// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjoi4tai_oNnk1SetMna9qaLbpn4mwMzI',
    appId: '1:970141986633:android:d20b08503b9ef92c9e3498',
    messagingSenderId: '970141986633',
    projectId: 'mountrip-6cebb',
    storageBucket: 'mountrip-6cebb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy25qyUFWOYURrmYWWxg0IrQdIB5gU6VE',
    appId: '1:970141986633:ios:4934a22f7b95380d9e3498',
    messagingSenderId: '970141986633',
    projectId: 'mountrip-6cebb',
    storageBucket: 'mountrip-6cebb.firebasestorage.app',
    androidClientId: '970141986633-e4iri0837imd62q286iolm5d6m7rmu7d.apps.googleusercontent.com',
    iosClientId: '970141986633-id83h5eara6duc5t5fdg1sr0pvn5tjsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mountrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy25qyUFWOYURrmYWWxg0IrQdIB5gU6VE',
    appId: '1:970141986633:ios:4934a22f7b95380d9e3498',
    messagingSenderId: '970141986633',
    projectId: 'mountrip-6cebb',
    storageBucket: 'mountrip-6cebb.firebasestorage.app',
    iosBundleId: 'com.example.mountrip',
  );
}